from .auth import auth_bp
from .dashboard import dashboard_bp
from .board import board_bp
from .investment import investment_bp
from .profile import profile_bp
from .payment import payment_bp
from .transaction import transaction_bp
from .notification import notification_bp
from .faq import faq_bp
from .market import market_bp